name: Update Homebrew Tap

on:
  release:
    types: [published]

jobs:
  update-tap:
    runs-on: ubuntu-latest
    steps:
      - name: Update Homebrew formula
        uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: ssmtui
          homebrew-tap: suraj16thjan/homebrew-tap
          download-url: https://github.com/suraj16thjan/ssmtui/archive/refs/tags/${{ github.event.release.tag_name }}.tar.gz
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
